[project]
name = "lgtm-cat-api"
version = "0.1.0"
description = "LGTMeowで利用するWebAPI"
authors = [
    { name = "kobayashi-m42", email = "m42kobayashi@gmail.com" }
]
dependencies = [
    "aiohttp>=3.13.2",
    "aioboto3>=15.5.0",
    "asyncmy>=0.2.10",
    "fastapi>=0.121.0",
    "greenlet>=3.2.4",
    "magika>=1.0.1",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
    "sentry-sdk>=2.43.0",
]
readme = "README.md"
requires-python = ">= 3.13"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
managed = true

[dependency-groups]
dev = [
    "ruff>=0.14.3",
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.0.0",
    "cryptography>=46.0.3",
    "types-aioboto3[s3]>=15.4.0",
    "types-python-jose>=3.5.0",
    "boto3-stubs[bedrock-runtime,s3vectors,rekognition]>=1.40.71",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.mypy]
explicit_package_bases = true
mypy_path = "src"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
